### PR TITLE
fix: Set TMPDIR to avoid disk space issues

### LINKED ISSUE #197: Consider option to set TMPDIR from action
I recently ran into https://github.com/NixOS/nix/issues/395, resulting in an unexpected "out of space" error when running a build in `nix-shell` despite there being plenty of space on the runner.

While I could set `TMPDIR` myself, it seems like it may be beneficial to set it from this action as the default nix behavior is not very GitHub Actions Runner friendly.

It seems like the best candidate is setting `TMPDIR` to `$RUNNER_TEMP`.

### PR DESCRIPTION
**Pull request by jalaziz**
Set `TMPDIR` if not already set to workaround potential disk space issues while running builds in a nix shell. See NixOS/nix#395 for more info.

fixes #197

### CODE REVIEW

File: install-nix.sh [hunk 1]
```diff
@@ -91,5 +91,10 @@ if [[ -n "${INPUT_NIX_PATH:-}" ]]; then
   echo "NIX_PATH=${INPUT_NIX_PATH}" >> "$GITHUB_ENV"
 fi
 
+# Set temporary directory (if not already set)
```
Comment (domenkozar) [inline install-nix.sh:94]:
```suggestion
# Set temporary directory (if not already set) to fix https://github.com/cachix/install-nix-action/issues/197
```

**Review by sandydoo — APPROVED** [review]
